BEGIN;

-- =========================================================
-- USERS
-- =========================================================

CREATE TABLE users (
  user_id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  first_name VARCHAR(100) NOT NULL,
  last_name VARCHAR(100) NOT NULL,
  email VARCHAR(255) NOT NULL UNIQUE,
  active BOOLEAN NOT NULL DEFAULT TRUE,
  created_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
  updated_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP
);

-- =========================================================
-- COMMITTEES
-- =========================================================

CREATE TABLE committees (
  committee_id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  committee_name VARCHAR(255) NOT NULL UNIQUE,
  active BOOLEAN NOT NULL DEFAULT TRUE
);

-- =========================================================
-- USER ROLES
-- =========================================================

CREATE TABLE user_roles (
  user_role_id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  user_id BIGINT NOT NULL,
  role VARCHAR(50) NOT NULL,
  effective_start_date DATE NOT NULL,
  effective_end_date DATE,
  active BOOLEAN NOT NULL DEFAULT TRUE,

  CONSTRAINT fk_user_roles_user
    FOREIGN KEY (user_id)
    REFERENCES users(user_id),

  CONSTRAINT chk_user_roles_dates
    CHECK (
      effective_end_date IS NULL
      OR effective_end_date >= effective_start_date
    )
);

-- =========================================================
-- USER COMMITTEES
-- =========================================================

CREATE TABLE user_committees (
  user_committee_id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  user_id BIGINT NOT NULL,
  committee_id BIGINT NOT NULL,
  committee_role VARCHAR(50) NOT NULL,
  effective_start_date DATE NOT NULL,
  effective_end_date DATE,
  active BOOLEAN NOT NULL DEFAULT TRUE,

  CONSTRAINT fk_user_committees_user
    FOREIGN KEY (user_id)
    REFERENCES users(user_id),

  CONSTRAINT fk_user_committees_committee
    FOREIGN KEY (committee_id)
    REFERENCES committees(committee_id),

  CONSTRAINT chk_user_committees_dates
    CHECK (
      effective_end_date IS NULL
      OR effective_end_date >= effective_start_date
    )
);

-- =========================================================
-- REPORT TEMPLATES
-- =========================================================

CREATE TABLE report_templates (
  report_template_id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  name VARCHAR(255) NOT NULL UNIQUE,
  description TEXT,
  active BOOLEAN NOT NULL DEFAULT TRUE
);

-- =========================================================
-- REPORT TEMPLATE VERSIONS
-- =========================================================

CREATE TABLE report_template_versions (
  report_template_id BIGINT NOT NULL,
  version INTEGER NOT NULL,
  created_by BIGINT NOT NULL,
  created_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
  active BOOLEAN NOT NULL DEFAULT TRUE,

  PRIMARY KEY (report_template_id, version),

  CONSTRAINT fk_template_versions_template
    FOREIGN KEY (report_template_id)
    REFERENCES report_templates(report_template_id),

  CONSTRAINT fk_template_versions_user
    FOREIGN KEY (created_by)
    REFERENCES users(user_id),

  CONSTRAINT chk_template_version_positive
    CHECK (version > 0)
);

-- =========================================================
-- QUESTIONS
-- =========================================================

CREATE TABLE questions (
  question_id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  question_code VARCHAR(100) NOT NULL UNIQUE,
  active BOOLEAN NOT NULL DEFAULT TRUE
);

-- =========================================================
-- QUESTION VERSIONS
-- =========================================================

CREATE TABLE question_versions (
  question_id BIGINT NOT NULL,
  version INTEGER NOT NULL,
  question_text TEXT NOT NULL,
  question_type VARCHAR(30) NOT NULL,
  created_by BIGINT NOT NULL,
  created_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
  active BOOLEAN NOT NULL DEFAULT TRUE,

  PRIMARY KEY (question_id, version),

  CONSTRAINT fk_question_versions_question
    FOREIGN KEY (question_id)
    REFERENCES questions(question_id),

  CONSTRAINT fk_question_versions_user
    FOREIGN KEY (created_by)
    REFERENCES users(user_id),

  CONSTRAINT chk_question_version_positive
    CHECK (version > 0),

  CONSTRAINT chk_question_type
    CHECK (
      question_type IN (
        'text',
        'textarea',
        'number',
        'date',
        'currency',
        'dropdown',
        'checkbox'
      )
    )
);

-- =========================================================
-- REPORT QUESTIONS
-- =========================================================

CREATE TABLE report_questions (
  report_template_id BIGINT NOT NULL,
  report_version INTEGER NOT NULL,
  question_id BIGINT NOT NULL,
  question_version INTEGER NOT NULL,
  section_name VARCHAR(255),
  display_order INTEGER NOT NULL,
  required BOOLEAN NOT NULL DEFAULT FALSE,
  created_by BIGINT NOT NULL,
  created_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
  active BOOLEAN NOT NULL DEFAULT TRUE,

  PRIMARY KEY (
    report_template_id,
    report_version,
    question_id,
    question_version
  ),

  CONSTRAINT fk_report_questions_template_version
    FOREIGN KEY (report_template_id, report_version)
    REFERENCES report_template_versions(report_template_id, version),

  CONSTRAINT fk_report_questions_question_version
    FOREIGN KEY (question_id, question_version)
    REFERENCES question_versions(question_id, version),

  CONSTRAINT fk_report_questions_user
    FOREIGN KEY (created_by)
    REFERENCES users(user_id),

  CONSTRAINT chk_report_question_order
    CHECK (display_order > 0)
);

-- =========================================================
-- REPORTS
-- =========================================================

CREATE TABLE reports (
  report_id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  report_template_id BIGINT NOT NULL,
  report_template_version INTEGER NOT NULL,
  committee_id BIGINT NOT NULL,
  created_by_user_id BIGINT NOT NULL,
  report_title VARCHAR(255) NOT NULL,
  reporting_period DATE,
  event_date DATE,
  status VARCHAR(30) NOT NULL DEFAULT 'draft',
  created_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
  updated_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
  locked BOOLEAN NOT NULL DEFAULT FALSE,
  locked_by_user_id BIGINT,
  locked_at TIMESTAMPTZ,
  pdf_path TEXT,
  pdf_created_by_user_id BIGINT,
  pdf_created_at TIMESTAMPTZ,

  CONSTRAINT fk_reports_template_version
    FOREIGN KEY (report_template_id, report_template_version)
    REFERENCES report_template_versions(report_template_id, version),

  CONSTRAINT fk_reports_committee
    FOREIGN KEY (committee_id)
    REFERENCES committees(committee_id),

  CONSTRAINT fk_reports_created_by
    FOREIGN KEY (created_by_user_id)
    REFERENCES users(user_id),

  CONSTRAINT fk_reports_locked_by
    FOREIGN KEY (locked_by_user_id)
    REFERENCES users(user_id),

  CONSTRAINT fk_reports_pdf_created_by
    FOREIGN KEY (pdf_created_by_user_id)
    REFERENCES users(user_id),

  CONSTRAINT chk_report_status
    CHECK (
      status IN (
        'draft',
        'submitted',
        'reviewed',
        'approved',
        'returned_for_changes',
        'locked',
        'archived',
        'other'
      )
    ),

  CONSTRAINT chk_report_lock_metadata
    CHECK (
      (locked = FALSE AND locked_by_user_id IS NULL AND locked_at IS NULL)
      OR
      (locked = TRUE AND locked_by_user_id IS NOT NULL AND locked_at IS NOT NULL)
    ),

  CONSTRAINT chk_report_pdf_requires_lock
    CHECK (
      pdf_path IS NULL
      OR locked = TRUE
    )
);

-- =========================================================
-- REPORT STATUS HISTORY
-- =========================================================

CREATE TABLE report_status_history (
  report_status_history_id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  report_id BIGINT NOT NULL,
  from_status VARCHAR(30),
  to_status VARCHAR(30) NOT NULL,
  changed_by_user_id BIGINT NOT NULL,
  changed_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
  comments TEXT,

  CONSTRAINT fk_report_status_history_report
    FOREIGN KEY (report_id)
    REFERENCES reports(report_id),

  CONSTRAINT fk_report_status_history_user
    FOREIGN KEY (changed_by_user_id)
    REFERENCES users(user_id),

  CONSTRAINT chk_status_history_from
    CHECK (
      from_status IS NULL
      OR from_status IN (
        'draft',
        'submitted',
        'reviewed',
        'approved',
        'returned_for_changes',
        'locked',
        'archived',
        'other'
      )
    ),

  CONSTRAINT chk_status_history_to
    CHECK (
      to_status IN (
        'draft',
        'submitted',
        'reviewed',
        'approved',
        'returned_for_changes',
        'locked',
        'archived',
        'other'
      )
    )
);

-- =========================================================
-- ANSWERS
-- =========================================================

CREATE TABLE answers (
  answer_id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  report_id BIGINT NOT NULL,
  question_id BIGINT NOT NULL,
  question_version INTEGER NOT NULL,
  answer_value TEXT,
  answer_date TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
  answered_by BIGINT NOT NULL,
  notes TEXT,

  CONSTRAINT fk_answers_report
    FOREIGN KEY (report_id)
    REFERENCES reports(report_id),

  CONSTRAINT fk_answers_question_version
    FOREIGN KEY (question_id, question_version)
    REFERENCES question_versions(question_id, version),

  CONSTRAINT fk_answers_user
    FOREIGN KEY (answered_by)
    REFERENCES users(user_id),

  CONSTRAINT uq_report_question_answer
    UNIQUE (report_id, question_id, question_version)
);

-- =========================================================
-- ATTACHMENTS
-- =========================================================

CREATE TABLE attachments (
  attachment_id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  report_id BIGINT NOT NULL,
  uploaded_by BIGINT NOT NULL,
  original_filename VARCHAR(255) NOT NULL,
  storage_key TEXT NOT NULL,
  mime_type VARCHAR(100) NOT NULL,
  file_size BIGINT NOT NULL,
  description TEXT,
  include_in_pdf BOOLEAN NOT NULL DEFAULT FALSE,
  uploaded_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
  active BOOLEAN NOT NULL DEFAULT TRUE,

  CONSTRAINT fk_attachments_report
    FOREIGN KEY (report_id)
    REFERENCES reports(report_id),

  CONSTRAINT fk_attachments_user
    FOREIGN KEY (uploaded_by)
    REFERENCES users(user_id),

  CONSTRAINT chk_attachment_file_size
    CHECK (file_size >= 0)
);

-- =========================================================
-- REPORT ACTION ITEMS
-- Repeatable structured Committee Report data
-- =========================================================

CREATE TABLE report_action_items (
  action_item_id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  report_id BIGINT NOT NULL,
  action_item TEXT NOT NULL,
  owner VARCHAR(255),
  due_date DATE,
  status VARCHAR(100),
  notes TEXT,
  display_order INTEGER NOT NULL DEFAULT 1,
  created_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
  updated_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,

  CONSTRAINT fk_action_items_report
    FOREIGN KEY (report_id)
    REFERENCES reports(report_id),

  CONSTRAINT chk_action_item_order
    CHECK (display_order > 0)
);

-- =========================================================
-- REPORT DATES TO REMEMBER
-- Repeatable structured Committee Report data
-- =========================================================

CREATE TABLE report_dates_to_remember (
  report_date_id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  report_id BIGINT NOT NULL,
  reminder_date DATE,
  item_deadline TEXT,
  owner VARCHAR(255),
  display_order INTEGER NOT NULL DEFAULT 1,
  created_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
  updated_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,

  CONSTRAINT fk_dates_to_remember_report
    FOREIGN KEY (report_id)
    REFERENCES reports(report_id),

  CONSTRAINT chk_report_date_order
    CHECK (display_order > 0)
);

-- =========================================================
-- REPORT BUDGET ITEMS
-- Repeatable structured Committee Report data
-- =========================================================

CREATE TABLE report_budget_items (
  budget_item_id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  report_id BIGINT NOT NULL,
  category VARCHAR(255),
  estimated_cost NUMERIC(12,2),
  actual_cost NUMERIC(12,2),
  notes TEXT,
  display_order INTEGER NOT NULL DEFAULT 1,
  created_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
  updated_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,

  CONSTRAINT fk_budget_items_report
    FOREIGN KEY (report_id)
    REFERENCES reports(report_id),

  CONSTRAINT chk_budget_estimated_cost
    CHECK (estimated_cost IS NULL OR estimated_cost >= 0),

  CONSTRAINT chk_budget_actual_cost
    CHECK (actual_cost IS NULL OR actual_cost >= 0),

  CONSTRAINT chk_budget_item_order
    CHECK (display_order > 0)
);

-- =========================================================
-- INDEXES
-- =========================================================

CREATE INDEX idx_user_roles_user
  ON user_roles(user_id);

CREATE INDEX idx_user_committees_user
  ON user_committees(user_id);

CREATE INDEX idx_user_committees_committee
  ON user_committees(committee_id);

CREATE INDEX idx_reports_committee
  ON reports(committee_id);

CREATE INDEX idx_reports_status
  ON reports(status);

CREATE INDEX idx_reports_reporting_period
  ON reports(reporting_period);

CREATE INDEX idx_reports_created_by
  ON reports(created_by_user_id);

CREATE INDEX idx_report_status_history_report
  ON report_status_history(report_id);

CREATE INDEX idx_report_status_history_changed_at
  ON report_status_history(changed_at);

CREATE INDEX idx_answers_report
  ON answers(report_id);

CREATE INDEX idx_answers_question
  ON answers(question_id, question_version);

CREATE INDEX idx_attachments_report
  ON attachments(report_id);

CREATE INDEX idx_action_items_report
  ON report_action_items(report_id);

CREATE INDEX idx_dates_to_remember_report
  ON report_dates_to_remember(report_id);

CREATE INDEX idx_budget_items_report
  ON report_budget_items(report_id);

COMMIT;